import React from "react";
import Form from "../forms/Form";
import Input from "../forms/Input";

export default function CardForm({ onSubmit, onReset, validateForm, title, errors, data, onInputChange }) {

    return (
        <Form
            onSubmit={onSubmit}
            onReset={onReset}
            validateForm={validateForm}
            title={title}
            styles={{ maxWidth: "800px" }}
        >
            <Input
                name="title"
                label="Title"
                error={errors.title}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="subtitle"
                label="Subtitle"
                error={errors.subtitle}
                onChange={onInputChange}
                data={data}
                sm={6}
                required={false}
            />
            <Input
                name="description"
                label="Description"
                error={errors.description}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="phone"
                label="Phone"
                type="phone"
                error={errors.phone}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="email"
                label="Email"
                type="email"
                error={errors.email}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="webUrl"
                label="Web URL"
                type="url"
                error={errors.webUrl}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="imageUrl"
                label="Image URL"
                error={errors.imageUrl}
                onChange={onInputChange}
                data={data}
                sm={6}
                required={false}
            />
            <Input
                name="imageAlt"
                label="Image ALT"
                error={errors.imageAlt}
                onChange={onInputChange}
                data={data}
                sm={6}
                required={false}
            />
            <Input
                name="state"
                label="state"
                error={errors.state}
                onChange={onInputChange}
                data={data}
                sm={6}
                required={false}
            />
            <Input
                label="country"
                name="country"
                error={errors.country}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="city"
                label="city"
                error={errors.city}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="street"
                label="street"
                error={errors.street}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="houseNumber"
                label="house Number"
                type="number"
                error={errors.houseNumber}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="zip"
                label="zip"
                error={errors.zip}
                onChange={onInputChange}
                data={data}
                sm={6}
                required={false}
            />
        </Form>
    );
}